// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDeEWFhu98idqqJ0rd1n4aoABs7FOLb9g',
    appId: '1:103110623583:web:fac25aa234583b397836ea',
    messagingSenderId: '103110623583',
    projectId: 'testpro-c6a16',
    authDomain: 'testpro-c6a16.firebaseapp.com',
    databaseURL: 'https://testpro-c6a16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testpro-c6a16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuN4iuKN8eISZY08Jpuae0madmTT-V1k',
    appId: '1:103110623583:android:b0b80ffce61b311a7836ea',
    messagingSenderId: '103110623583',
    projectId: 'testpro-c6a16',
    databaseURL: 'https://testpro-c6a16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testpro-c6a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvVqvblJUEHP19PFh24RS49eu8_4PD6-M',
    appId: '1:103110623583:ios:dc1a50b6ebeaf46c7836ea',
    messagingSenderId: '103110623583',
    projectId: 'testpro-c6a16',
    databaseURL: 'https://testpro-c6a16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testpro-c6a16.appspot.com',
    iosClientId: '103110623583-n2tqellndcmvbejcfq51ps9mmcaqtcl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvVqvblJUEHP19PFh24RS49eu8_4PD6-M',
    appId: '1:103110623583:ios:dc1a50b6ebeaf46c7836ea',
    messagingSenderId: '103110623583',
    projectId: 'testpro-c6a16',
    databaseURL: 'https://testpro-c6a16-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testpro-c6a16.appspot.com',
    iosClientId: '103110623583-n2tqellndcmvbejcfq51ps9mmcaqtcl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPro',
  );
}
